name: Maple
version: '1.0-SNAPSHOT'
main: team.azalea.maple.MaplePlugin
api-version: '1.21'
authors: [ Azalea Team ]
depend: [ LuckPerms ]
description: Core utilities for servers under the Azalea network. Manages punishments, chat filtering, and other things.
website: https://azalea.team/
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.0
  - org.jetbrains.kotlin:kotlin-reflect:2.1.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.20.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.20.0
  - com.moandjiezana.toml:toml4j:0.7.2
  - org.flywaydb:flyway-core:10.16.0
