# custom minimessage color codes to use in messages
[colors]
p = "#EFEFEF"
s = "#FBB13C"
t = "#FF5700"
br = "#742F04"
error = "#FF6E6E"
# purple for punishments
pr = "#9248df"

[custom_placeholders]
prefix = "<t>Maple <br>|<p>"
error = "<error>❌<#ff7f6e>"
success = "<#bfffc6>✔"
discord_url = "https://discord.azalea.team/"
discord = "<click:open_url:\"https://discord.azalea.team/\"><#7289da><u>Discord</u>"

[en.chatFilter]
message = "<s>[Filter] <p>{username}</p> sent: {message} (<p>{action}</p>)"

[en.staffchat]
message = "<s>[Staff] <p>{player}<gray>:</gray></p> {message}"

[en.broadcasts]
all = [
    """


        <#7289da>★ <st>                                                              </st> <#7289da>★</#7289da>
           <#7eb8d6><b>DISCORD</b></#7eb8d6>

          <white>| <gray>Our community is on <#7289da>[{discord}]</#7289da>!</gray>
          <white>| <gray>Join us for updates, giveaways and give us feedback!</gray>

        <#7289da>★ <st>                                                              </st> <#7289da>★</#7289da>

    """,
    """


        <#bfffc6>💰 <st>                                                              </st> <#bfffc6>💰<#bfffc6>
           <#bfffc6><b>STORE</b></#bfffc6>

            <white>| <gray>Purchase ranks on our <#bfffc6><click:open_url:\"https://store.azalea.team/\">[<u>Store</u>]</click></#bfffc6>!</gray>

        <#bfffc6>💰 <st>                                                              </st> <#bfffc6>💰<#bfffc6>

    """,
    """


       <#FFE563>★ <st>                                                              </st> <#FFE563>★<#FFE563>
          <#FFE563><b>FAVORITE</b><#FFE563>

         <white>| <gray>If you like the server, make sure to /favorite it!</gray>
         <white>| <gray>This allows you to find the server later!</gray>

       <#FFE563>★ <st>                                                              </st> <#FFE563>★<#FFE563>

   """,
]

[en.rules]
all = [
    """
    <b><gradient:#9bd9f2:#578a9e>POKE <#56889C>Rules</#56889C><reset>

    <b>1.</b> Be respectful
    <b>2.</b> No NSFW content
    <b>3.</b> No threats
    <b>4.</b> No advertisements
    <b>5.</b> No hacking
    <b>6.</b> No abusing bugs or exploits

    <#19911d>For further info, continue reading >
    """,
    """
        <b><gradient:#9bd9f2:#578a9e>POKE <#56889C>Rules</#56889C><reset>

        <b>1. Be respectful</b>

        Discrimination in any form is not tolerated anywhere on Airbrush.
        Being disrespectful to others, instigating arguments, attacking
        people especially for no reason are also not welcome.
        Also no swearing!
    """,
    """
        <b><gradient:#9bd9f2:#578a9e>POKE <#56889C>Rules</#56889C><reset>

        <b>2. No NSFW content</b>

        NSFW topics or themes are not allowed.
        Politics are discouraged as it is a near guarantee of turning hostile.
    """,
    """
        <b><gradient:#9bd9f2:#578a9e>POKE <#56889C>Rules</#56889C><reset>

        <b>3. No threats</b>

        This includes any sort of threat, joke or not, and will be reported directly to Minehut.
    """,
    """
        <b><gradient:#9bd9f2:#578a9e>POKE <#56889C>Rules</#56889C><reset>

        <b>4. No advertising</b>

        Please do not advertise other servers, Discord servers, websites, etc.
    """,
    """
        <b><gradient:#9bd9f2:#578a9e>POKE <#56889C>Rules</#56889C><reset>

        <b>5. No hacking</b>

        Please don't hack.

        By hacking, you prove to everyone that you're a noob and incapable of playing a game like a normal person. <3
    """,
    """
        <b><gradient:#9bd9f2:#578a9e>POKE <#56889C>Rules</#56889C><reset>

        <b>6. No abusing bugs or exploits</b>

        If you find a bug or exploit anywhere in Poke, please let us know and don't abuse them.
    """
]

[en.commands]
setSpawn = "{success} Set spawn location!"

[en.commands.discord]
base = "{success} Join us on Discord <click:open_url:\"https://discord.azalea.team/\"><#7289da><u>here</u>!"

[en.commands.fly]
self = "{success} You're now able to fly!"
other = "{success} {target} is now able to fly!"

[en.commands.flyspeed]
self = "{success} You've set your fly speed to <b>{speed}</b>!"
other = "{success} You've set the fly speed of {target} to {speed}!"
invalid = "{error} Invalid speed! Please use a value between -10 and 10."

[en.commands.gamemode]
self = "{success} You've switched to {gamemode} mode!"
other = "{success} {target} has switched to {gamemode} mode!"
alreadySelf = "{error} You're already in {gamemode} mode!"
alreadyOther = "{error} {target} is already in {gamemode} mode!"

[en.commands.maple]
base = """
    {prefix} Maple Core - by <t><click:open_url:"https://azalea.team/">azalea.team</click></t>
"""
reload = "{success} Reloaded translations!"

[en.punishments]
invalidId = "{error} {id} is not a valid punishment ID!"
log = "<hover:show_text:'<p>View punishment</p>'><click:run_command:/punishment {id}><gray><p>{moderator}</p> {type} <p>{player}</p> - <red>{short_reason}</red> [{duration_uppercase}]"
kickLog = "<hover:show_text:'<p>View punishment</p>'><click:run_command:/punishment {id}><gray><p>{moderator}</p> {type} <p>{player}</p> - <red>{short_reason}</red>"
playerBanned = """
        <s>You are banned for <error>{short_reason} <#B0B0B0>[{duration}]<s>.

        <p>Description:<s> {long_reason}

        <s>If you believe this is false, you may appeal on our {discord} <s>server in the <p>#tickets <s>channel.
"""
playerMuted = """
        {error} {long_reason} <#B0B0B0>[{duration}]<s>.

        <s>If you believe this is false, you may appeal on our Discord server ({discord_url}) in the <p>#tickets <s>channel.
"""
playerKicked = """
        <s>You were kicked for <error>{short_reason}<s>.

        <p>Description:<s> {long_reason}
"""
playerAutoBanned = """
        <s>You were automatically banned for <error>{short_reason} <#B0B0B0>[{duration}]<s>.

        <p>Description:<s> {long_reason}

        <s>If you believe this is false, you may appeal on our Discord server ({discord_url}) in the <p>#tickets <s>channel.
"""


[en.punishments.commands.ban]
alreadyBanned = "{error} {target} is already banned!"
error = "{error} {reason}"

[en.punishments.commands.kick]
error = "{error} {reason}"

[en.punishments.commands.mute]
alreadyMuted = "{error} {target} is already muted!"
error = "{error} {reason}"

[en.punishments.commands.view]
all = """
            <pr>Username:</pr>
            {player}

            <pr>Punishments:</pr>
            {punishments}
"""
overview = """
            <pr>Username:</pr>
            {player}
            <pr>Punished by:</pr>
            {moderator}

            <pr>Punishment:</pr>
            {reason} <em>{type_uppercase}</em>

            <pr>Details:</pr>
            <hover:show_text:'<p>Expires at'>Exp</hover>: {expires_at}
            Status: {status_capitalized}

                 <pr><hover:show_text:'<p>View all punishments of {player}'><click:run_command:/punishments {player}>Go back</hover> <gray>|</gray> <hover:show_text:'<p>Manage this punishment'><click:run_command:/editpunishment {id}>Edit</hover>
"""
notes = """
            <pr>Notes:</pr>
            {notes}
"""
reverted = """
            <pr>Reverted:</pr>
            {reverted_reason}

            <pr>Reverted by:</pr>
            {reverted_by}
"""

[en.punishments.commands.revert]
provideMessage = "Provide a reason for reverting the punishment:"
success = "{success} Successfully reverted the punishment!"
error = "{error} {reason}"
log = "<hover:show_text:'<s>View punishment'><click:run_command:/punishment {id}><gray><s>{moderator}</s> reverted <s>{player}</s> - <red>{reason}</red>"

[en.punishments.commands.edit.items.revert]
text = "<red>Revert"
lore = "<s>Revert this punishment"
noReversion = "<red>Kicks cannot be reverted."
alreadyReverted = """
    <red>This punishment has already been reverted!
"""

[en.punishments.commands.edit.items.reason]
text = "<p>Edit Reason"
lore = "<s>Edit the reason for this punishment"
input = "<s>Enter the new reason below:"
success = "<success>Successfully edited reason."

[en.punishments.commands.edit.items.duration]
text = "<p>Edit duration"
lore = "<s>Edit the duration for this punishment"
noEditDuration = "<red>Kicks cannot have a duration."
input = """
    <s>Enter the new duration below (ex: 1h):
"""
success = "<success>Successfully edited duration."

[en.punishments.commands.edit.items.notes]
text = "<p>Edit Notes"
lore = "<s>Edit the notes for this punishment"
input = """
    <s>Enter your note below:
"""
success = "<success>Successfully edited notes."
noClearPermission = """
    {error} You do not have permission to clear notes.
"""
cleared = "<success>Successfully cleared notes."
clearCancelled = "{error}Cancelled clearing notes."
confirmClear = """
    <s>Please enter <g>yes</g> to confirm:
"""

[en.punishments.commands.punish]
hasActivePunishment = "{error} This player already has an active punishment! Click <click:run_command:/punishment {id}><u>here</u></click> to view it."
initial = """
             <pr>Username:</pr>
             {player}

             <pr>What are you punishing for? (p.{current_page})</pr>
             {punishments}
"""
confirm = """
             <pr>Username:</pr>
             {player}

             <pr>You are punishing this player for:</pr>
             {reason} <em>{type}</em>

             <pr>Confirm & Issue:</pr>

             <dark_green><click:run_command:/punish {player} {short} confirm>ISSUE</click></dark_green>

             <dark_red><click:run_command:/punish {player} {short} cancel>CANCEL</click></dark_red>
"""
success = "{success} Successfully punished player."
error = "{error} {reason}"
