# custom minimessage color codes to use in messages
[colors]
p = "#EFEFEF"
s = "#FBB13C"
t = "#FF5700"
br = "#742F04"
error = "#FF6E6E"

[custom_placeholders]
prefix = "<t>Maple <br>|<p>"
error = "<error>❌<#ff7f6e>"
success = "<#bfffc6>✔"
discord = "<click:open_url:\"https://discord.azalea.team/\"><#7289da><u>Discord</u>"

[en.commands.fly]
self = "{success} You're now able to fly!"
other = "{success} {target} is now able to fly!"

[en.commands.flyspeed]
self = "{success} You've set your fly speed to <b>{speed}</b>!"
other = "{success} You've set the fly speed of {target} to {speed}!"
invalid = "{error} Invalid speed! Please use a value between -10 and 10."

[en.commands.gamemode]
self = "{success} You've switched to {gamemode} mode!"
other = "{success} {target} has switched to {gamemode} mode!"
alreadySelf = "{error} You're already in {gamemode} mode!"
alreadyOther = "{error} {target} is already in {gamemode} mode!"

[en.commands.maple]
base = """
    {prefix} Maple Core - by <t><click:open_url:"https://azalea.team/">azalea.team</click></t>
"""
reload = "{success} Reloaded translations!"

[en.punishments]
playerBanned = """
        <s>You are banned for <error>{short_reason} <#B0B0B0>[{duration}]<s>.

        <p>Description:<s> {long_reason}

        <s>If you believe this is false, you may appeal on our {discord} <s>server in the <p>#tickets <s>channel.
"""
playerMuted = """
        {error} {full_reason} <#B0B0B0>[{duration}]<s>.

        <s>If you believe this is false, you may appeal on our {discord} <s>server in the <p>#tickets <s>channel.
"""
playerKicked = """
        <s>You were kicked for <error>{short_reason}<s>.

        <p>Description:<s> {long_reason}
"""

[en.punishments.commands.ban]
alreadyBanned = "{error} {target} is already banned!"
