# custom minimessage color codes to use in messages
[colors]
p = "#EFEFEF"
s = "#FBB13C"
t = "#FF5700"
br = "#742F04"

[custom_placeholders]
prefix = "<t>Maple <br>|<p>"
error = "<#ff6e6e>❌<#ff7f6e>"
success = "<#bfffc6>✔"

[en.commands.fly]
self = "{success} You're now able to fly!"
other = "{success} {target} is now able to fly!"

[en.commands.flyspeed]
self = "{success} You've set your fly speed to <b>{speed}</b>!"
other = "{success} You've set the fly speed of {target} to {speed}!"
invalid = "{error} Invalid speed! Please use a value between -10 and 10."

[en.commands.gamemode]
self = "{success} You've switched to {gamemode} mode!"
other = "{success} {target} has switched to {gamemode} mode!"
alreadySelf = "{error} You're already in {gamemode} mode!"
alreadyOther = "{error} {target} is already in {gamemode} mode!"

[en.commands.maple]
base = """
    {prefix} Maple Core - by <t><click:OPEN_URL:https://azalea.team/>azalea.team</click></t>
"""
reload = "{success} Reloaded translations!"

[en.punishments]
playerBanned = """
    woah u were banned from the server by {moderator}
"""

[en.punishments.commands.ban]
alreadyBanned = "{error} That player is already banned!"