# custom minimessage color codes to use in messages
[colors]
p = "#EFEFEF"
s = "#FBB13C"
t = "#FF5700"
br = "#742F04"
error = "#FF6E6E"
# purple for punishments
pr = "#9248df"

[custom_placeholders]
prefix = "<t>Maple <br>|<p>"
error = "<error>❌<#ff7f6e>"
success = "<#bfffc6>✔"
discord = "<click:open_url:\"https://discord.azalea.team/\"><#7289da><u>Discord</u>"

[en.commands.fly]
self = "{success} You're now able to fly!"
other = "{success} {target} is now able to fly!"

[en.commands.flyspeed]
self = "{success} You've set your fly speed to <b>{speed}</b>!"
other = "{success} You've set the fly speed of {target} to {speed}!"
invalid = "{error} Invalid speed! Please use a value between -10 and 10."

[en.commands.gamemode]
self = "{success} You've switched to {gamemode} mode!"
other = "{success} {target} has switched to {gamemode} mode!"
alreadySelf = "{error} You're already in {gamemode} mode!"
alreadyOther = "{error} {target} is already in {gamemode} mode!"

[en.commands.maple]
base = """
    {prefix} Maple Core - by <t><click:open_url:"https://azalea.team/">azalea.team</click></t>
"""
reload = "{success} Reloaded translations!"

[en.punishments]
invalidId = "{error} {id} is not a valid punishment ID!"
playerBanned = """
        <s>You are banned for <error>{short_reason} <#B0B0B0>[{duration}]<s>.

        <p>Description:<s> {long_reason}

        <s>If you believe this is false, you may appeal on our {discord} <s>server in the <p>#tickets <s>channel.
"""
playerMuted = """
        {error} {full_reason} <#B0B0B0>[{duration}]<s>.

        <s>If you believe this is false, you may appeal on our {discord} <s>server in the <p>#tickets <s>channel.
"""
playerKicked = """
        <s>You were kicked for <error>{short_reason}<s>.

        <p>Description:<s> {long_reason}
"""

[en.punishments.commands.ban]
alreadyBanned = "{error} {target} is already banned!"

[en.punishments.commands.view]
all = """
            <pr>Username:</pr>
            {player}

            <pr>Punishments:</pr>
            {punishments}
"""
overview = """
            <pr>Username:</pr>
            {player}
            <pr>Punished by:</pr>
            {moderator}

            <pr>Punishment:</pr>
            {reason} <em>{type_uppercase}</em>

            <pr>Details:</pr>
            <hover:show_text:'<p>Expires at'>Exp</hover>: {expires_at}
            Status: {status_capitalized}

                 <pr><hover:show_text:'<p>View all punishments of {player}'><click:run_command:/punishments {player}>Go back</hover> <gray>|</gray> <hover:show_text:'<p>Manage this punishment'><click:run_command:/editpunishment {id}>Edit</hover>
"""
notes = """
            <pr>Notes:</pr>
            {notes}
"""
reverted = """
            <pr>Reverted:</pr>
            {reverted_reason}

            <pr>Reverted by:</pr>
            {reverted_by}
"""

[en.punishments.commands.revert]
provideMessage = "Provide a reason for reverting the punishment:"
success = "{success} Successfully reverted the punishment!"
error = "{error} {reason}"
log = "<hover:show_text:'<s>View punishment'><click:run_command:/punishment {id}><gray><s>{moderator}</s> reverted <s>{player}</s> - <red>{reason}</red>"

[en.punishments.commands.edit.items.revert]
text = "<red>Revert"
lore = "<s>Revert this punishment"
noReversion = "<red>Kicks cannot be reverted."
alreadyReverted = """
    <red>This punishment has already been reverted!
"""

[en.punishments.commands.edit.items.reason]
text = "<p>Edit Reason"
lore = "<s>Edit the reason for this punishment"
success = "<success>Successfully edited reason."

[en.punishments.commands.edit.items.duration]
text = "<p>Edit duration"
lore = "<s>Edit the duration for this punishment"
noEditDuration = "<red>Kicks cannot have a duration."
input = """
    <s>Enter the new duration below (ex: 1h):
"""
success = "<success>Successfully edited duration."

[en.punishments.commands.edit.items.notes]
text = "<p>Edit Notes"
lore = "<s>Edit the notes for this punishment"
input = """
    <s>Enter your note below:
"""
success = "<success>Successfully edited notes."
noClearPermission = """
    <error>You do not have permission to clear notes.
"""
cleared = "<success>Successfully cleared notes."
clearCancelled = "<error>Cancelled clearing notes."
confirmClear = """
    <s>Please enter <g>yes</g> to confirm:
"""